param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference = 'Stop'
$manifest = Get-Content -LiteralPath (Join-Path $ProjectRoot 'course-manifest.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$index = [ordered]@{}
foreach ($lesson in @($manifest.parts.topics)) {
  $path = Join-Path $ProjectRoot ($lesson.path -replace '/', '\')
  $html = Get-Content -LiteralPath $path -Raw -Encoding UTF8
  $html = [regex]::Replace($html, '<!--[\s\S]*?-->', ' ')
  $html = [regex]::Replace($html, '<(script|style)\b[^>]*>[\s\S]*?</\1>', ' ', 'IgnoreCase')
  $html = [regex]::Replace($html, '<head\b[^>]*>[\s\S]*?</head>', ' ', 'IgnoreCase')
  $text = [regex]::Replace($html, '<[^>]+>', ' ')
  $text = [System.Net.WebUtility]::HtmlDecode($text)
  $index[$lesson.id] = [regex]::Replace($text, '\s+', ' ').Trim()
}
$json = $index | ConvertTo-Json -Compress
$content = "// Generated by scripts/build-search-index.ps1. Do not edit manually.`nwindow.COURSE_SEARCH_INDEX = Object.freeze($json);`n"
$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $ProjectRoot 'assets\search-index.js'), $content, $utf8)
Write-Output "Generated search index for $($index.Count) lessons"
